### ISSUE TITLE
SDK throws error on asynchronous workflow execution

### ISSUE THREAD

**Issue by ksatzke** [knix-microfunctions/knix#59]
## Context:
when calling execute_async in https://github.com/knix-microfunctions/knix/blob/master/mfn_sdk/mfn_sdk/workflow.py, 
it throws "AttributeError: 'MfnClient' object has no attribute 'host'" on bare metal installation when executing:

> return Execution(self.client, self.client.host+r.headers['Location'])

 ## Expected Behaviour
execute_async should return an object usable for querying for asynchronous execution results

**Comment by iakkus** [comment]
I think this might have already been fixed in the 'develop' branch.

Need a test to check that.

**Comment by ksatzke** [comment]
just checked out develop branch to check - does not fix, the same statement now throws "KeyError: 'location'".

**Comment by iakkus** [comment]
Test added and fixed in 'develop'.

**Comment by manuelstein** [comment]
> Test added and fixed in 'develop'.

I had also started working on this and fixed different things in frontend.go.
You've pushed this to k-list, can we merge this?
